#ifndef QWBATTERYPLUGIN_GLOBAL_H
#define QWBATTERYPLUGIN_GLOBAL_H

#if defined(QWBATTERYPLUGIN_LIBRARY)
#  define QWBATTERYPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define QWBATTERYPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // QWBATTERYPLUGIN_GLOBAL_H
